### ISSUE TITLE
Botplay arrow animation

### ISSUE THREAD

**Issue by lemz1** [GithubSPerez/the-shaggy-mod#22]
Hi,
I noticed that not all the arrows light up in botplay and I know

If this wants to be fixed then just go to PlayState.hx (line 4527)

It should say `StrumPlayAnim(false, Std.int(Math.abs(note.noteData)) % 4, time);`

change `4` with `9`
(in the end looks like this `StrumPlayAnim(false, Std.int(Math.abs(note.noteData)) % 9, time);`)

then it plays the right arrow animations

**Comment by nintendofan44** [comment]
its not 4 with 9
it 4 with **Main.ammo[mania]**

**Comment by nintendofan44** [comment]
i wont get in any fight but i had this idea for fixing this first
**the correct way**
unlike you guys
