### ISSUE TITLE
Midis and BF samples

### ISSUE THREAD

**Issue by Juarez2010** [GithubSPerez/the-shaggy-mod#24]
Do you think I could get the midis for all the songs in the mod? (yes, including big shot that's in the source files) Also, for Thunderstorm, BF sounds a bit different so do you think I can get the samples and chromatics for that? Just asking. Take all the time you need.

**Comment by dum-du-m** [comment]
just a note, thunderstorm and disassembler werent made by perez so i dont think he has em

**Comment by Juarez2010** [comment]
Oh, ok. Thanks for letting me know.
